### ISSUE TITLE
SpaceInvaders.java shadowing of baddieSpeed

### ISSUE THREAD

**Issue by hensonm1** [finneyj/Invaders#2]
Line 6, baddie speed is set, then line 34, it is set again :(

**Comment by finneyj** [comment]
Indeed. 

This is to support multiple waves of the game. Note that the speed of the baddies change with time:
https://github.com/finneyj/Invaders/blob/main/SpaceInvaders.java#L103

Hence, line 34 is needed to ensure the speed is reset when a new wave of alien invaders arrive...

Regarding line 6, always good practice to ensure all the instance variables of a class are set to a know, valid state when an object is created.
